// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhuI95zx-L-hl6uRSktESYtupIR_ubAY',
    appId: '1:28251173277:web:c1ef944c875453ddc17f74',
    messagingSenderId: '28251173277',
    projectId: 'beersp-deb52',
    authDomain: 'beersp-deb52.firebaseapp.com',
    storageBucket: 'beersp-deb52.firebasestorage.app',
    measurementId: 'G-B8TD4FB167',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nCbMPAaR_KDQ9aNPICqTOrFzAuRj664',
    appId: '1:28251173277:android:e51e4acb74fad87bc17f74',
    messagingSenderId: '28251173277',
    projectId: 'beersp-deb52',
    storageBucket: 'beersp-deb52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlT7vpmhj8c3IigLFQQgWzhdO_0GxdZy8',
    appId: '1:28251173277:ios:9f5fbe48c644f453c17f74',
    messagingSenderId: '28251173277',
    projectId: 'beersp-deb52',
    storageBucket: 'beersp-deb52.firebasestorage.app',
    iosBundleId: 'com.example.beerspDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlT7vpmhj8c3IigLFQQgWzhdO_0GxdZy8',
    appId: '1:28251173277:ios:9f5fbe48c644f453c17f74',
    messagingSenderId: '28251173277',
    projectId: 'beersp-deb52',
    storageBucket: 'beersp-deb52.firebasestorage.app',
    iosBundleId: 'com.example.beerspDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMhuI95zx-L-hl6uRSktESYtupIR_ubAY',
    appId: '1:28251173277:web:2d3703834a7d41e1c17f74',
    messagingSenderId: '28251173277',
    projectId: 'beersp-deb52',
    authDomain: 'beersp-deb52.firebaseapp.com',
    storageBucket: 'beersp-deb52.firebasestorage.app',
    measurementId: 'G-2XS2FNQLEX',
  );
}
